### PR TITLE
feat: add cem analyzer

### LINKED ISSUE #48: [feat]: add custom-elements-manifest analyzer
Steps:
1. add `@custom-elements-manifest/analyzer` as devdep to all templates
2. add `analyze` script to all templates
3. profit 

cc @thepassle

### PR DESCRIPTION
**Pull request by bennypowers**
closes #48

## What I did

1. add cem/a as a devdependency in common
2. add analyze script in common
3. add customElements package.json key in common
3. add custom-elements.json to gitignore in common
4. add analyze to build and publish steps in various packages
5. add `scriptRunCommand` to all templates
6. analyze the generated package after installing deps
7. add test 
8. require node >= 14
9. add `--help` switch
10. remove "extends" docs from README (see https://github.com/open-wc/open-wc/pull/2270)
11. add args table to README

TODO
- [x] tests

## `--help` output

```
        _.,,,,,,,,,._
     .d''           ``b.       Open Web Components Recommendations
   .p'      Open       `q.
 .d'    Web Components  `b.    Start or upgrade your web component project with
 .d'                     `b.   ease. All our recommendations at your fingertips.
 ::   .................   ::
 `p.                     .q'
  `p.    open-wc.org    .q'
   `b.     @openWc     .d'
     `q..            ..,'      See more details at https://open-wc.org/init/
        '',,,,,,,,,,''



Usage

  $ npm init @open-wc [<options>]

Options

  --destinationPath path                        The path the generator will write files to
  --type scaffold|upgrade                       Choose scaffold to create a new project or upgrade to add features to an
                                                existing project
  --scaffoldType wc|app                         The type of project to scaffold. wc for a single published component, app for
                                                an application
  --features linting|testing|demoing|building   Which features to include. linting, testing, demoing, or building
  --typescript true|false                       Whether to use TypeScript in your project
  --tagName string                              The tag name for the web component or app shell element
  --installDependencies yarn|npm|false          Whether to install dependencies. Choose npm or yarn to install with those
                                                package managers, or false to skip installation
  --writeToDisk true|false                      Whether or not to actually write the files to disk
  --help                                        This help message
```
## Questions
- should the step which analyzes the package after install happen in every case (e.g. via `npx`)? even if not installing?
- under this pr, analyzer is not optional, everyone always gets it. cool?

### CODE REVIEW

**Comment by bennypowers** [comment]
@thepassle fails in node 12 b/c of optional chaining in cem/a
so either we bump requirements to 14 or build/refactor cem/a, right?

**Comment by thepassle** [comment]
Is there any particular reason why we use node 12? I think we can just upgrade right?

Im really averse to adding a build step to cem/a

**Comment by bennypowers** [comment]
upgrading means requiring users to be on node 14

- [firebase](https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version) supports node 14
- [gcp](https://cloud.google.com/functions/docs/concepts/nodejs-runtime) supports node 14
- [azure](https://docs.microsoft.com/en-us/azure/app-service/configure-language-nodejs?pivots=platform-linux#code-try-3) supports node 14
- [aws](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) supports node 14
- [heroku](https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version) uses 14 by default
- [qovery]() ???
- [vercel](https://vercel.com/docs/runtimes#official-runtimes/node-js) uses 14 by default
I'm super happy to make this breaking change. @LarsDenBakker ?

**Comment by bennypowers** [comment]
WARNING: either don't squash, or make sure the merge commit is a `feat!:`

**Review by thepassle — APPROVED** [review]

**Pull request merged**
